id: P010728
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4872
  title: སྡོམ་གསུམ་རྩ་བ་དང་དེའི་འགྲེལ་པ་དཔག་བསམ་སྙེ་མ་སོགས།
  author: ''
  volumes:
    1f8ede7684ae4202b5a5079904133981:
      image_group_id: I3CN4874
      title: ''
      volume_number: 1
      total_pages: 624
      base_file: v001.txt
