id: P010728
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:21:48.287688
source_metadata:
  id: bdr:W3CN4872
  title: སྡོམ་གསུམ་རྩ་བ་དང་དེའི་འགྲེལ་པ་དཔག་བསམ་སྙེ་མ་སོགས།
  author: ''
  volumes:
    1f8ede7684ae4202b5a5079904133981:
      image_group_id: I3CN4874
      title: ''
      volume_number: 1
      total_pages: 624
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
